### PR TITLE
Make it easier to reuse code targeting specific user groups

### PR DESCRIPTION
**Pull request by Salanto**
This also has an example that makes moderation easier by sending mods an altered version of the global message to include a user IPID.

### CODE REVIEW

**Comment by in1tiate** [comment]
looks good, though I'd rather these selective targeting versions of broadcast and such had different names to differentiate them more clearly

**Review by in1tiate — CHANGES_REQUESTED** [review]
see above

**Comment by Salanto** [comment]
Usually, I would agree with you, but that would cause the code to be clogged up with multiple functions where the only difference is the ACL we check. This at least sums them up in one function and switches are fast enough that this should not cause any noticeable difference between a direct call.

**Comment by in1tiate** [comment]
alrighty then

**Pull request merged**
