### PR TITLE
Add a multiclient limit for local connections

### PR DESCRIPTION
**Pull request by dmcnvbgfgh-cancer**

### CODE REVIEW

**Comment by scatterflower** [comment]
keep in mind that all websocket connections appear as local connections, until their IP is changed. be sure to account for this.

**Comment by stonedDiscord** [comment]
why disallow the serverhost from multiclienting

this makes no sense

**Comment by dmcnvbgfgh-cancer** [comment]
@stonedDiscord 
I dunno, but the original code reads:
```cpp
TODO: make this configurable
```
@scatterflower Thanks, I'll revise it accordingly.

**Comment by scatterflower** [comment]
> 
> 
> @stonedDiscord
> I dunno, but the original code reads:
> 
> ```c++
> // TODO: make this configurable
> ```
> 
> @scatterflower Thanks, I'll revise it accordingly.

i think i actually meant that in reference to the multiclient limit not being a fixed value, and once it was actually implemented, i forgot to remove the todo lmao

**Pull request closed without merging**
